### ISSUE TITLE
GPL-3 isn't generally advisable for JavaScript

### ISSUE THREAD

**Issue by coolaj86** [wmerfalen/js-utils#1]
People don't use GPL in node or browser JavaScript because it creates too many legal questions and complications.

v8 compiles down to assembly. JScript / WSL runs interpreted. Web pages include multiple files that use each other, but aren't intended to be coupled, but end up as binary at runtime. Etc. What would be the requirements for Electron where a binary tarball includes the code, but it's not strictly "linked" into the distributable binary?

It's not worth the risk of "infecting" a project with legal risks to use a rand function or an array shuffle.

If you want a copyleft license, consider MPL-2.0 which is like the LGPL, but without the stigma.

Most people use MIT, but this is not really a good license for open source since it doesn't specify patent grants and such. Apache-2.0 is generally a good license.

Or `(MIT or Apache-2.0)`.

[CC0-1.0](https://therootcompany.com/blog/how-to-release-software-into-the-public-domain/) is also a good choice for the public domain for small utility functions the likes of which can be found on StackOverflow, or written in a few lines.

**Comment by wmerfalen** [comment]
Changing to MIT. Thank you!
