### ISSUE TITLE
It is cryptographically secure

### ISSUE THREAD

**Issue by coolaj86** [wmerfalen/js-utils#2]
`Math.random()` is cryptographically secure in all modern JavaScript engines, and node.js.

It is not guaranteed to be cryptographically secure in embedded interpreters - such as CouchDB, [Duktape](https://duktape.org), etc.

However, due to various [lawsuits](https://www.sitepoint.com/microsoft-fix-their-non-random-browser-choice-screen/) and [other complications](https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d), everyone typically backs it with same backing as WebCrypto or node's crypto.

**Comment by wmerfalen** [comment]
Updated my README. Will post in a few minutes.
